### ISSUE TITLE
Always the same name surname

### ISSUE THREAD

**Issue by ghost** [a-tsagkalidis/fictional_names_package#1]
Example:
>>>from fictional_names import name_generator
>>> names = name_generator.generate_name
>>> names()
'Cedric of Dunland'
>>> names = name_generator.generate_name
>>> names()
'Cedric of Dunland'

or
>>> names(gender='female', style='germanic', library=True)
'Edda Klein'
>>> name_generator.generate_name(gender='female', style='germanic', library=True)
'Edda Klein'

The function always returns the same values.

**But generally a great function for generating names!**

**Comment by a-tsagkalidis** [comment]
Yeah, indeed, if you run the `generate_function` using python from terminal side, then all the names/surnames are already chosen from the .py files, where the names or the prefixes/suffixes are present. That results for the function to use the same variables every time it runs.

Executing the function within a .py file on the other hand, solves that bug, because the function uses refreshed variables.

Anyway, I have spotted that flaw within the code, and soon enough I'll give it a shot fixing it!

Thanks a lot for sharing that :)

**Comment by ghost** [comment]
Wow, what a fast answer!

My python program looks like this:

```
from fictional_names import name_generator

names = name_generator.generate_name

names()

name1  = names(style='germanic', library=True)
name2  = name_generator.generate_name(style='germanic', library=True)
name3  = name_generator.generate_name(style='germanic', library=True)

print('name 1:', name1, 'name 2:', name2, 'name 3:', name3)
```

The output looks like this:
name 1: Brunhild Ludwig name 2: Brunhild Ludwig name 3: Brunhild Ludwig

From my point of view, the behavior also applies to code in a .py.
Maybe I'm doing something wrong...

**Comment by a-tsagkalidis** [comment]
True.. the library was initially designed to be used as part of program that generates one name of every style on every run.
I'll keep you informed as soon I'll fix this bug.

Thanks again for the feedback! :)

**Comment by a-tsagkalidis** [comment]
> Wow, what a fast answer!
> 
> My python program looks like this:
> 
> ```
> from fictional_names import name_generator
> 
> names = name_generator.generate_name
> 
> names()
> 
> name1  = names(style='germanic', library=True)
> name2  = name_generator.generate_name(style='germanic', library=True)
> name3  = name_generator.generate_name(style='germanic', library=True)
> 
> print('name 1:', name1, 'name 2:', name2, 'name 3:', name3)
> ```
> 
> The output looks like this: name 1: Brunhild Ludwig name 2: Brunhild Ludwig name 3: Brunhild Ludwig
> 
> From my point of view, the behavior also applies to code in a .py. Maybe I'm doing something wrong...

The bug has been fixed. You may upgrade your version of the package using `pip install fictional_names --upgrade` and give it a shot :)

**Comment by ghost** [comment]
Now it works fine.
The output is now f.e.
name 1: Silke Sturm name 2: Helgard Winter name 3: Eduarda Seidel

**Thank you for the fast fix!!!**
